import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Gulf Careerist Admin",
  description: "Generated by sanity io",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="corporate">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
