import '../globals.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./layout/Navbar";
import { Footer } from "./layout/Footer";
import Providers from './providers'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gulf Careerist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="corporate">
      <body className={inter.className}>
        <Providers>
          <Header />
          <main className="min-h-screen justify-center   px-4  py-8    ">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
