import '../globals.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./layout/Header";
import { Footer } from "./layout/Footer";
import Providers from './providers'
import ThemeSwitcher from './components/ThemeSwitcher'
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gulf Careerist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="corporate">
      <body className={inter.className}>
        <Providers>
          <Header/>
        {/* <header className='py-6'>
            <nav className='container flex items-center justify-between'>
              <ul>
                <li>
                  <Link href='/'>Home</Link>
                </li>
              </ul>
              <ThemeSwitcher />
            </nav>
          </header> */}
          <main className='container flex items-center justify-between'>
            {children}
          </main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
